version: '3.3'
# This is used for development purposes only.
# This docker-compose will allow live editing
# of the codebase without having to rebuild the
# container. it does this by mounting the twdb
# folder from the host machine.
services:
  app:
    build:
      context: .
      args:
        # Change this password when you fork this or don't blame me!!!
        SSH_PASS: ${SSH_PASS:-ZAWeRM22mx7JoHsRZO8Qk59XVlaNWcXr}
        URL: ${URL:-localhost}
        #BUILD_ENV: ${BUILD_ENV:-test}
        #USE_SSHD: ${USE_SSHD:-1}
        #USE_VOLUME: ${USE_VOLUME:-1}
    ports:
      - "80:80"
      - "23:22"
    volumes:
      - ./data/:/var/data/
